---
title: "Cleaning"
author: "Alex Kan, Jessica Ho, Katherine Wang, Ishan Shah, Svetak Sundhar"
date: "April 20, 2018"
output:
  pdf_document: default
  html_document: default---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
```

```{r, eval = F}
# Read in original sample of 1/10 of Yelp Kaggle Datset 
sample <- fread("sample.csv")

# Read in kaggle tables 
hours <- read.csv("C:/Users/lexokan/Desktop/Yelp/yelp_business_hours.csv", fill = T)
business <- fread("C:/Users/lexokan/Desktop/Yelp/yelp_business.csv")
user<- fread("C:/Users/lexokan/Desktop/Yelp/yelp_user.csv")

```

```{r, eval = F}
sample <- merge(sample, business, by = "business_id", all = T)
sample <- merge(sample, hours, by = "business_id", all = T)
sample <- merge(sample, user, by = "user_id")

#write.csv(sample, "sample3.csv")
```

```{r}
df <- fread("C:/Users/lexokan/Desktop/Yelp/sample3.csv")
vegasDemographics <- read.csv("data/vegasDemographics.csv")
phoenixDemographics <- read.csv("data/phoenixDemographics.csv")
```

```{r}
vegasDemographics$FIPS <- as.character(vegasDemographics$FIPS)
phoenixDemographics$FIPS <- as.character(phoenixDemographics$FIPS)
colnames(vegasDemographics)[2] <- "postal_code"
colnames(phoenixDemographics)[2] <- "postal_code"

# Read in zipcodes of cities within a 30 mile radius of Las Vegas demograhpics and Phoenix Demograhpics

vegas <- df[, 2:51] %>% 
    select(-c(V1, neighborhood, state, name.y, friends, elite, address)) %>% 
    filter(str_detect(categories, "Restaurants"), postal_code %in% vegasDemographics$postal_code) %>% 
    select(-c(text, categories, monday, tuesday, wednesday, thursday, friday, saturday, sunday)) %>% 
    merge(., vegasDemographics, by = "postal_code", all = T) %>% 
    select(-Name) %>% 
    na.omit(temp)



phoenix <- df[, 2:51] %>% 
    select(-c(V1, neighborhood, state, name.y, friends, elite, address)) %>% 
    filter(str_detect(categories, "Restaurants"), postal_code %in% phoenixDemographics$postal_code) %>% 
    select(-c(text, categories, monday, tuesday, wednesday, thursday, friday, saturday, sunday)) %>% 
    merge(., phoenixDemographics, by = "postal_code", all = T) %>% 
    select(-Name) %>% 
    na.omit(temp)

#stars.y = business
#average_starts = per used 

colnames(phoenix) <- c("zip", "userID", "businessID", "reviewID", "reviewStars", "date", "usefulBusi", "funnyBusi",
                       "coolBusi", "businessName", "city", "lat", "long", "averageReviewBusiness", "reviewCountBusiness",
                       "isOpen", "reviewCountUser", "yelpingSince", "usefulUser", "funnyUser", "coolUser", "fans",
                       "averageReviewUser", "hotComp", "moreComp", "profileComp", "cuteComp", "listComp", "noteComp",
                       "plainComp", "coolComp", "funnyComp", "writerComp", "photosComp", "percAsian", "percBlack",
                       "percWhite", "percHispanic", "percNHW", "zipPopulation", "zipYouthPopulation", 
                       "medianIncome", "percBachelors")

colnames(vegas) <- c("zip", "userID", "businessID", "reviewID", "reviewStars", "date", "usefulBusi", "funnyBusi",
                       "coolBusi", "businessName", "city", "lat", "long", "averageReviewBusiness", "reviewCountBusiness",
                       "isOpen", "reviewCountUser", "yelpingSince", "usefulUser", "funnyUser", "coolUser", "fans",
                       "averageReviewUser", "hotComp", "moreComp", "profileComp", "cuteComp", "listComp", "noteComp",
                       "plainComp", "coolComp", "funnyComp", "writerComp", "photosComp", "percAsian", "percBlack",
                       "percWhite", "percHispanic", "percNHW", "zipPopulation", "zipYouthPopulation", 
                       "medianIncome", "percBachelors")

#write.csv(phoenix, "data/phoenix.csv")
#write.csv(vegas, "data/vegas.csv")

```

